---
- hosts: vm
  sudo: true
  vars:
    timezone: UTC
  vars_files:
    - vars/geerlingguy-php.yml
    - vars/geerlingguy-ruby.yml
    - vars/geerlingguy-apache.yml
    - vars/geerlingguy-varnish.yml
    - vars/geerlingguy-solr.yml
    - vars/geerlingguy-xdebug.yml
    - vars/geerlingguy-mysql.yml
  roles:
    - m1r1k-common-packages
    - geerlingguy.git
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.java
    - geerlingguy.tomcat6
#    - geerlingguy.solr
#    - m1r1k-solr-config
    - geerlingguy.memcached
    - geerlingguy.php-memcached
    - geerlingguy.varnish
    - geerlingguy.ruby
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.xdebug
